labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Models/FriendModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IT_Lab3_2022.Models
{
    public class FriendModel
    {
        public int Id { get; set; }

        [Required]
        [Range(0, 200, ErrorMessage ="Id must be a number from 0 and 200")]
        [Display(Name = "Friend ID.")]
        public int Friend_Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Ime { get; set; }

        [Required]
        [Display(Name = "Place")]
        public string MestoZiveenje { get; set; }
    }
}

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Controllers/FriendController.cs
using IT_Lab3_2022.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IT_Lab3_2022.Controllers
{
    public class FriendController : Controller
    {
        private static List<FriendModel> friendsList = new List<FriendModel>
        {
            new FriendModel()
            {
                Friend_Id = 0,
                Ime = "Maja",
                MestoZiveenje = "Skopje"
            },
            new FriendModel()
            {
                Friend_Id = 1,
                Ime = "Daniel",
                MestoZiveenje = "Veles"
            },
            new FriendModel()
            {
                Friend_Id = 2,
                Ime = "Stojance",
                MestoZiveenje = "Bitola"
            }
        };

        // GET: Friend
        public ActionResult ShowFriends()
        {
            return View(friendsList);
        }

        public ActionResult AddFriend()
        {
            FriendModel model = new FriendModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult AddFriend(FriendModel model)
        {
            if (ModelState.IsValid == false)
            {
                return View("AddFriend", model);
            }
            friendsList.Add(model);
            return View("ShowFriends", friendsList);
        }

        public ActionResult UpdateFriend(int id)
        {
            var model = friendsList.ElementAt(id);
            model.Id = id;
            return View(model);
        }

        [HttpPost]
        public ActionResult UpdateFriend(FriendModel model)
        {
            if(ModelState.IsValid == false)
            {
                return View("AddFriend", model);
            }
            var update = friendsList.ElementAt(model.Id);
            update.Ime = model.Ime;
            update.MestoZiveenje = model.MestoZiveenje;
            return View("ShowFriends", friendsList);
        }

        public ActionResult DeleteFriend(int id)
        {
            friendsList.RemoveAt(id);
            return View("ShowFriends", friendsList);
        }
    }
}

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IT_Lab3_2022.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Views/Friend/AddFriend.cshtml
@model IT_Lab3_2022.Models.FriendModel
@{
    ViewBag.Title = "AddFriend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add friend</h2>

@using (Html.BeginForm("AddFriend", "Friend"))
{
    <div class="form-group">
        @Html.LabelFor(f => f.Friend_Id)
        @Html.TextBoxFor(f => f.Friend_Id, new { @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(f => f.Friend_Id)
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.Ime)
        @Html.TextBoxFor(f => f.Ime, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.Ime)
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.MestoZiveenje)
        @Html.TextBoxFor(f => f.MestoZiveenje, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.MestoZiveenje)
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button>
        @Html.ActionLink("Back", "ShowFriends", new {@class = "btn btn-default"})
    </div>


}

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Views/Friend/ShowFriends.cshtml
@model List<IT_Lab3_2022.Models.FriendModel>
@{
    ViewBag.Title = "ShowFriends";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All friends</h2>

    <table class="table table-bordered table-responsive">
        <thead>
            <tr>
                <td>Friend ID.</td>
                <td>Friend Name</td>
                <td>Place</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @{ 
                int i = 0;
                foreach (var friend in Model)
                {
                    friend.Id = i++;
                    <tr>
                        <td>@friend.Friend_Id</td>
                        <td>@friend.Ime</td>
                        <td>@friend.MestoZiveenje</td>
                        <td>
                            @Html.ActionLink("Edit", "UpdateFriend", new { id = friend.Id }, new {@class="btn btn-default"})
                            @Html.ActionLink("Delete", "DeleteFriend", new { id = friend.Id}, new {@class = "btn btn-default"})
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Views/Friend/UpdateFriend.cshtml
@model IT_Lab3_2022.Models.FriendModel
@{
    ViewBag.Title = "UpdateFriend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update friend</h2>

@using (Html.BeginForm("UpdateFriend", "Friend"))
{
    <div class="form-group">
        @Html.LabelFor(f => f.Friend_Id)
        @Html.TextBoxFor(f => f.Friend_Id, new { @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(f => f.Friend_Id)
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.Ime)
        @Html.TextBoxFor(f => f.Ime, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.Ime)
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.MestoZiveenje)
        @Html.TextBoxFor(f => f.MestoZiveenje, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.MestoZiveenje)
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-default">Update</button>
        @Html.ActionLink("Back", "ShowFriends", new { @class = "btn btn-default" })
    </div>


}

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

labs/lab3/IT_Lab3_2022/IT_Lab3_2022/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Friends Application", "ShowFriends", "Friend", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Show Friends", "ShowFriends", "Friend")</li>
                    <li>@Html.ActionLink("Add Friend", "AddFriend", "Friend")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>